name: 'CI Multiplatform Build'

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  ubuntu64:
    name: 'Linux/Ubuntu 64-bit'
    runs-on: [ubuntu-18.04]
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v2.3.3
      - name: Install prerequisites (Apt)
        shell: bash
        run: |
          sudo apt-get -qq update
          sudo apt-get install -y \
          build-essential \
          cmake \
          qtbase5-dev \
          qtbase5-private-dev \
          ffmpeg
          sudo add-apt-repository ppa:obsproject/obs-studio
          sudo apt-get update
          sudo apt install obs-studio
      - name: 'Configure'
        shell: bash
        run: |
          mkdir ./build
          cd ./build
          cmake -DBUILD_UBUNTU=yes ..
      - name: 'Build'
        shell: bash
        working-directory: ${{ github.workspace }}/build
        run: make -j${NPROC:-4}


