name: 'CI Multiplatform Build'

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  ubuntu64:
    name: 'Build_Linux'
    runs-on: [ubuntu-18.04]
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v2.3.3
      - name: 'Install dependencies'
        shell: bash
        working-directory: ${{ github.workspace }}
        run: ./ci/linux/install-dependencies-ubuntu.sh
      - name: 'Build Plugin'
        shell: bash
        working-directory: ${{ github.workspace }}
        run: ./ci/linux/build-ubuntu.sh
      - name: 'Package Plugin'
        shell: bash
        working-directory: ${{ github.workspace }}
        run: ./ci/linux/package-ubuntu.sh
  macos:
    name: 'Build_macos'
    runs-on: [macos-latest]
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v2.3.3
      - name: 'Install dependencies'
        shell: bash
        working-directory: ${{ github.workspace }}
        run: ./ci/macos/install-dependencies-macos.sh
      - name: 'Build OBS'
        shell: bash
        working-directory: ${{ github.workspace }}
        run: ./ci/macos/install-build-obs-macos.sh
      - name: 'Build Plugin'
        shell: bash
        working-directory: ${{ github.workspace }}
        run: ./ci/macos/build-macos.sh
      



